"""
Offline fallback: make the existing XiaoxiaoNeural result lines sound more
childlike + emotional WITHOUT any network, by phase-vocoder pitch shifting.

The true neural child voice (zh-CN-XiaomengNeural) is generated by gen_voices.py
and needs the build proxy (127.0.0.1:45361). Until that proxy is reachable, this
script derives a "cute + emotional" version straight from the current WAVs:

  - base +N semitones  -> higher, younger timbre (childlike)
  - win  : brighter & faster   (higher pitch, speed 0.92)
  - lose : softer  & slower    (lower pitch,  speed 1.10)
  - draw : neutral             (just the child shift)

Output overwrites app/src/main/res/raw/voice_*.wav (16-bit mono @ 44.1 kHz).
"""

import numpy as np
import wave

SRC = "app/src/main/res/raw/voice_{}.wav"

# (event, total semitones, speed)  -- speed<1 faster, >1 slower
PARAMS = [
    ("win",  6.0, 0.92),
    ("lose", 2.5, 1.10),
    ("draw", 4.0, 1.00),
]


def read_wav(path: str):
    with wave.open(path, "rb") as w:
        n = w.getnframes()
        raw = w.readframes(n)
        data = np.frombuffer(raw, dtype=np.int16).astype(np.float32) / 32768.0
    return data


def write_wav(path: str, data: np.ndarray) -> None:
    pcm = np.clip(data, -1.0, 1.0)
    pcm = (pcm * 32767.0).astype(np.int16)
    with wave.open(path, "wb") as w:
        w.setnchannels(1)
        w.setsampwidth(2)
        w.setframerate(44100)
        w.writeframes(pcm.tobytes())


def resample_linear(x: np.ndarray, n: int) -> np.ndarray:
    if n == len(x):
        return x
    idx = np.linspace(0, len(x) - 1, n)
    return np.interp(idx, np.arange(len(x)), x)


def phase_vocoder(x: np.ndarray, alpha: float, N: int = 2048, H: int = 512):
    """Pitch-scale x by `alpha` (alpha>1 = higher) keeping duration ~unchanged."""
    x = np.asarray(x, dtype=np.float64)
    if len(x) < N:
        return x
    w = np.hanning(N)
    x = np.concatenate([x, np.zeros(N)])  # pad so frames cover the tail
    n_frames = 1 + (len(x) - N) // H
    if n_frames < 2:
        return x[: len(x)]
    idx = np.arange(N)[None, :] + H * np.arange(n_frames)[:, None]
    frames = x[idx] * w
    X = np.fft.rfft(frames, N, axis=1)
    nb = X.shape[1]
    omega = 2 * np.pi * H * np.arange(nb) / N  # expected analysis phase advance
    Y = np.zeros_like(X)
    prev_analy = np.angle(X[0])
    synth = prev_analy.copy()
    Y[0] = np.abs(X[0]) * np.exp(1j * synth)
    for i in range(1, n_frames):
        analy = np.angle(X[i])
        dev = analy - prev_analy - omega
        dev = dev - 2 * np.pi * np.round(dev / (2 * np.pi))  # wrap to [-pi, pi]
        synth = synth + alpha * omega + dev
        Y[i] = np.abs(X[i]) * np.exp(1j * synth)
        prev_analy = analy
    yf = np.fft.irfft(Y, N, axis=1) * w
    out = np.zeros((n_frames - 1) * H + N)
    for i in range(n_frames):
        out[i * H : i * H + N] += yf[i]
    return out[: len(x)]


def process(x: np.ndarray, semitones: float, speed: float) -> np.ndarray:
    # Pre-compensate the later resample (speed) so final pitch == 2**(semis/12).
    alpha = 2 ** (semitones / 12.0) * speed
    y = phase_vocoder(x, alpha)
    y = resample_linear(y, int(round(len(x) * speed)))
    # Match input loudness, then clamp.
    rms_in = np.sqrt(np.mean(x ** 2)) + 1e-9
    rms_out = np.sqrt(np.mean(y ** 2)) + 1e-9
    y = y * (rms_in / rms_out)
    return np.clip(y, -1.0, 1.0)


def main() -> None:
    for event, semis, speed in PARAMS:
        src = SRC.format(event)
        x = read_wav(src)
        y = process(x, semis, speed)
        write_wav(src, y)
        print(
            f"{event}: shift {semis:+.1f}st speed {speed:.2f}x -> "
            f"{len(y)/44100:.2f}s"
        )


if __name__ == "__main__":
    main()
